### ISSUE TITLE
videonow_dec.c won't compile correctly

### ISSUE THREAD

**Issue by srilanka195** [paulguy/minitools#2]
Using Ming W compiler to compiler. Might be some errors in lines of code?
![error](https://user-images.githubusercontent.com/70341153/91478377-b9880580-e86d-11ea-85ad-aed7df350382.jpg)

**Comment by paulguy** [comment]
Should compile now.  I was being silly and clever and I guess an update to gcc made it stop compiling.  I also fixed those warnings because there's more silliness.  I don't know whether this functions anymore though, I saw some questionable things but I don't have the original files for it anymore to test/debug it.

**Comment by srilanka195** [comment]
Worked perfect! Thank you.

**Comment by srilanka195** [comment]
Works perfect! Thank you.
